User.create([
  { email: 'hatakekakashi@hljhs.com', password: '12345', first_name: 'Kakashi', last_name: 'Hatake', role: 'teacher', school: 'Hidden Leaf JHS' },
  { email: 'sarutobihiruzen@hljhs.com', password: '12345', first_name: 'Hiruzen', last_name: 'Sarutobi', role: 'teacher', school: 'Hidden Leaf JHS' },
  { email: 'uzumakinaruto@hljhs.com', password: '12345', first_name: 'Naruto', last_name: 'Uzumaki', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'uchihasasuke@hljhs.com', password: '12345', first_name: 'Sasuke', last_name: 'Uchiha', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'harunosakura@hljhs.com', password: '12345', first_name: 'Sakura', last_name: 'Haruno', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'narashikamaru@hljhs.com', password: '12345', first_name: 'Shikamaru', last_name: 'Nara', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'yamanakaino@hljhs.com', password: '12345', first_name: 'Ino', last_name: 'Yamanaka', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'hyuganeji@hljhs.com', password: '12345', first_name: 'Neji', last_name: 'Hyuga', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'leerock@hljhs.com', password: '12345', first_name: 'Rock', last_name: 'Lee', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'akimichichoji@hljhs.com', password: '12345', first_name: 'Choji', last_name: 'Akimichi', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'inuzukakiba@hljhs.com', password: '12345', first_name: 'Kiba', last_name: 'Inuzuka', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'aburameshino@hljhs.com', password: '12345', first_name: 'Shino', last_name: 'Aburame', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'hyugahinata@hljhs.com', password: '12345', first_name: 'Hinata', last_name: 'Hyuga', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'izumotenma@hljhs.com', password: '12345', first_name: 'Tenma', last_name: 'Izumo', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'uchihaitachi@hljhs.com', password: '12345', first_name: 'Itachi', last_name: 'Uchiha', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'inarishinko@hljhs.com', password: '12345', first_name: 'Shinko', last_name: 'Inari', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'abumizaku@hljhs.com', password: '12345', first_name: 'Zaku', last_name: 'Abumi', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'tsuchikin@hljhs.com', password: '12345', first_name: 'Kin', last_name: 'Tsuchi', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'yakushikabuto@hljhs.com', password: '12345', first_name: 'Kabuto', last_name: 'Yakushi', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'tsurugimisumi@hljhs.com', password: '12345', first_name: 'Misumi', last_name: 'Tsurugi', role: 'student', school: 'Hidden Leaf JHS' },
  { email: 'akadoyoroi@hljhs.com', password: '12345', first_name: 'Yoroi', last_name: 'Akado', role: 'student', school: 'Hidden Leaf JHS' },
])
